// Code generated by mockery v2.40.1. DO NOT EDIT.

package service

import (
	mail "manga-explorer/internal/infrastructure/mail"

	mock "github.com/stretchr/testify/mock"
)

// MailMock is an autogenerated mock type for the IMail type
type MailMock struct {
	mock.Mock
}

type MailMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MailMock) EXPECT() *MailMock_Expecter {
	return &MailMock_Expecter{mock: &_m.Mock}
}

// SendEmail provides a mock function with given fields: _a0
func (_m *MailMock) SendEmail(_a0 *mail.Mail) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*mail.Mail) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MailMock_SendEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmail'
type MailMock_SendEmail_Call struct {
	*mock.Call
}

// SendEmail is a helper method to define mock.On call
//   - _a0 *mail.Mail
func (_e *MailMock_Expecter) SendEmail(_a0 interface{}) *MailMock_SendEmail_Call {
	return &MailMock_SendEmail_Call{Call: _e.mock.On("SendEmail", _a0)}
}

func (_c *MailMock_SendEmail_Call) Run(run func(_a0 *mail.Mail)) *MailMock_SendEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*mail.Mail))
	})
	return _c
}

func (_c *MailMock_SendEmail_Call) Return(_a0 error) *MailMock_SendEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MailMock_SendEmail_Call) RunAndReturn(run func(*mail.Mail) error) *MailMock_SendEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMailMock creates a new instance of MailMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailMock {
	mock := &MailMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
