with-expecter: true
inpackage: true
dir: "{{.InterfaceDir}}/mocks"
mockname: '{{trimPrefix .InterfaceName "I"}}Mock'
packages:
  manga-explorer/internal/domain/users/repository:
    config:
      recursive: true
      all: true
  manga-explorer/internal/domain/users/service:
    config:
      recursive: true
      all: true
  manga-explorer/internal/infrastructure/file/service:
    config:
      recursive: true
      all: true
  manga-explorer/internal/infrastructure/mail/service:
    config:
      recursive: true
      all: true
  manga-explorer/internal/domain/mangas/repository:
    config:
      recursive: true
      all: true
  manga-explorer/internal/domain/mangas/service:
    config:
      recursive: true
      all: true
