with-expecter: true
inpackage: true
dir: "{{.InterfaceDir}}/mocks"
mockname: '{{trimPrefix .InterfaceName "I"}}Mock'
packages:
  manga-explorer/internal/domain/users/repository:
    config:
      recursive: true
      all: true
