basePath: /api/v1
definitions:
  dto.ErrorResponse:
    properties:
      code:
        type: integer
      details: {}
      message:
        type: string
    type: object
  dto.ResponsePage:
    properties:
      elements:
        type: integer
      page:
        type: integer
      total_elements:
        type: integer
      total_page:
        type: integer
    type: object
  dto.SuccessResponse:
    properties:
      code:
        type: integer
      data: {}
      page:
        $ref: '#/definitions/dto.ResponsePage'
    type: object
info:
  contact:
    email: arcorium.l@gmail.com
    name: arcorium
    url: github.com/arcorium
  description: Simple manga explorer used to read manga and save the manga
  title: Manga Explorer API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: login to get token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: login
      tags:
      - auth
      - account
swagger: "2.0"
